# ChatGPT Web adapter (normalized)
tool_id: web_chatgpt
version: 1.0.0
trust_tier: "B"
description: "Interact with ChatGPT through the web interface"
verbs:
  - id: web_chatgpt.new
    description: Start a new chat
    args:
      type: object
      properties:
        headless:
          type: boolean
          default: false
          description: Whether to run in headless mode (no visible browser)
      additionalProperties: false
    returns:
      type: object
      properties:
        chatId:
          type: string
          description: Unique identifier for the chat session
        url:
          type: string
          format: uri
          description: URL of the new chat
  - id: web_chatgpt.send
    description: Send a message to the current chat
    args:
      type: object
      required: [message]
      properties:
        message:
          type: string
          description: Message to send to ChatGPT
        waitForResponse:
          type: boolean
          default: true
          description: Whether to wait for and return the response
        timeout:
          type: integer
          minimum: 1000
          default: 30000
          description: Maximum time to wait for response in milliseconds
      additionalProperties: false
    returns:
      type: object
      properties:
        response:
          type: string
          description: ChatGPT's response (if waitForResponse is true)
        success:
          type: boolean
          description: Whether the message was sent successfully
  - id: web_chatgpt.history
    description: Get the chat history
    args:
      type: object
      properties:
        limit:
          type: integer
          minimum: 1
          maximum: 100
          default: 10
          description: Maximum number of messages to return
      additionalProperties: false
    returns:
      type: object
      properties:
        messages:
          type: array
          items:
            type: object
            properties:
              role:
                type: string
                enum: ["user", "assistant"]
              content:
                type: string
              timestamp:
                type: string
                format: date-time
  - id: web_chatgpt.clear
    description: Clear the current chat
    confirm: true
    args:
      type: object
      properties: {}
      additionalProperties: false
    returns:
      type: object
      properties:
        success:
          type: boolean

